name: demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.4
  email_validator: ^2.1.17
  flow_builder: ^0.0.9
  flutter_svg: ^2.0.5
  simple_shadow: ^0.3.1
  glassmorphism: ^3.0.0
  formz: ^0.6.0
  form_input: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/.
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
